algoritmo "segunda_aula"
// Função : Calcular a Média de dois números
// Autor : Lucas de Souza Santos
// Data : 25/11/2020
// Seção de Declarações 
var
   N1, N2, Media: Real
inicio
// Seção de Comandos 
   Escreva("Informe o Primeiro número: ")
   Leia(N1)
   Escreva("Informe o Segundo número: ")
   Leia(N2)
   
   Media <- (N1 + N2) / 2
   
   Escreva("A média de ", N1, " e ", N2, " é igual à ", Media)
   
fimalgoritmo
