algoritmo "semnome"
// Função : Somar dois números
// Autor : Lucas de Souza Santos
// Data : 25/11/2020
// Seção de Declarações
var
     N1, N2, soma: Inteiro
inicio
// Seção de Comandos

   Escreva("Informe um numero: ")
   Leia(N1)
   Escreva("Informe outro numero: ")
   Leia(N2)

   soma <- N1 + N2
   // aqui é somado de N1 e N2 será armazenada na variável soma

   Escreva("A soma de ", N1, " e ", N2, " é ", soma)

fimalgoritmo
