algoritmo "procedimento com passagem de parêmetro"
// Função :
// Autor :
// Data : 06/12/2020
// Seção de Declarações 
var
   x, y, produto: inteiro

Procedimento soma(A, B: Inteiro)
var
   produto: inteiro
inicio
      Escreval("Produto: ", produto)
      Escreval("A soma de ", A, " e ", B, " é ", A + B)
FimProcedimento
inicio
// Seção de Comandos

   produto <- 0
   Escreval(produto)
   x <- 5
   y <- 3
   soma(x, y)
fimalgoritmo
