algoritmo "Exercicio 4"
// Função : Exercicio 4
// Autor : Lucas de Souza Santos
// Data : 26/11/2020
// Seção de Declarações 
var
   num1, num2, soma: inteiro
inicio
// Seção de Comandos 
   Escreva("Digite um valor: ")
   Leia(num1)
   Escreva("Digite outro valor: ")
   Leia(num2)
   
   soma <- num1 + num2
   
   Escreval("A soma entre ", num1, " e ", num2, " é igual a ", soma,".")
fimalgoritmo
