algoritmo "Exercicio 2"
// Função : Ler o nome do usuário
// Autor : Lucas de Souza Santos
// Data : 26/11/2020
//  Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de
//  boas-vindas para ela:
//  Ex: Qual é o seu nome? João da Silva Olá João da Silva, é um prazer te conhecer!
var
   nome: caractere
inicio
      Escreval("Qual é o seu nome? ")
      Leia(nome)
      Escreva("Olá ", nome, ", é um prazer te conhecer!")
fimalgoritmo
